# Generated by Django 3.0.5 on 2020-04-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='question_text',
        ),
    ]
