# Generated by Django 3.0.5 on 2020-04-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200407_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='matches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='swipesiminterestedin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='them', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='swipesinterestedinme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='app.Person'),
        ),
    ]
